FROM mysql:latest

# keinos/sqlite3:latest
# add quotation to works as they are act_object
# finish replace IDs in act table


# do the dance with person / institutions

# and then with the lit branch *yay*
